project:
  type: book
  output-dir: _book
site-url: https://urbandesigntudelft.github.io/ouagb-m/
base-url: /ouagb-m/
book:
  title: 'Open Urban Analysis Guidebook: Morphology'
  author:
  - name: Giambattista Nolli
    orcid: 0000-0003-1689-0557
    email: bill@gates.com
    affiliations:
    - name: The Morphology Foundation
      city: Rome
  date: 10/23/2025
  chapters:
  - index.qmd
  - chapters/foundations_frontiers.qmd
  - part: Approach
    chapters:
    - chapters/map_based.qmd
    - chapters/experience_based.qmd
    - chapters/data_based.qmd
    # - chapters/index.qmd
    # - chapters/methodology/methodology.qmd
    # - chapters/methodology/3d_scanning_lidar.qmd
    # - chapters/methodology/typology_construction_quantitative.qmd
    # - chapters/methodology/typology_construction_qualitative.qmd
    # - chapters/methodology/techniques.qmd
    # - leaflet_template.qmd
  - part: Examples
    chapters:
    - catalog/index.qmd
    - text: "**The Concise Townscape**"                        #map
      file: catalog/examples/concise_townscape.qmd
    - text: "**Les Bastides: d’Aquitaine, du Bas-Languedoc et du Béarn**" #map
      file: catalog/examples/les_bastides.qmd
    - text: "**The Memory of the City**"                       #map
      file: catalog/examples/memory_of_the_city.qmd
    - text: "**Image of the City**"                            #experience
      file: catalog/examples/image_of_the_city.qmd
    - text: "**Notes on the Synthesis of Form**"               #data
      file: catalog/examples/synthesis_of_form.qmd
    - text: "**Urban Taxonomy**"                               #data/map
      file: catalog/examples/urban_taxonomy.qmd
    - text: "**Spacematrix**"                                 #data/map
      file: catalog/examples/space_matrix.qmd
    - text: "**Space Syntax**"                                 #data/map
      file: catalog/examples/space_syntax.qmd
    - text: "**3D Scanning and Lidar**"                        #data/experience
      file: catalog/examples/3d_scanning_lidar.qmd
    - catalog/examples/roma_al_tempo_di_benedetto.qmd
    - catalog/examples/stadtebau.qmd
    - catalog/examples/ville_radieuse.qmd
    - catalog/examples/studi_per_una_operante.qmd
    - catalog/examples/las_vegas.qmd
    - catalog/examples/bologna.qmd
    - catalog/examples/collage_city.qmd
    - catalog/examples/elements_urbaine.qmd
    - catalog/examples/versailles.qmd
    - catalog/examples/stedelijk_bouwwerk.qmd
    - catalog/examples/verstedelijkt_landschap.qmd
    - catalog/examples/la_metropole_imaginaire.qmd
    - catalog/examples/landschap_en_verstedelijking.qmd
    - catalog/examples/gli_orizzonti.qmd
    - catalog/examples/point_city.qmd
    - catalog/examples/paris_des_faubourgs.qmd
    - catalog/examples/het_land_in_de_stad.qmd
    - catalog/examples/stadsportretten.qmd
    - catalog/examples/zee_van_land.qmd
    - catalog/examples/bindels_gietema.qmd
    - catalog/examples/costa_iberica.qmd
    - catalog/examples/een_nieuwe_oude_jas.qmd
    - catalog/examples/belvedere_bouwen.qmd
    - catalog/examples/ijburg.qmd
    - catalog/examples/mobility.qmd
    - catalog/examples/haarlemmermeer.qmd
    - catalog/examples/evolution_of_a_compact_city.qmd
    - catalog/examples/measuring_pompeii.qmd
    - catalog/examples/object_van_beweging.qmd
    - catalog/examples/the_view_from_the_road.qmd
    - catalog/examples/kumbh_mela.qmd
  - part: "Appendices"
    chapters:
    - appendices/references.qmd

  page-footer:
    center: © 2025, Section of Urban Design TU Delft - CC BY 4.0
license: CC BY
bibliography: references.bib
format:
  html:
    theme:
    - journal
    - brand
    toc: true
    lightbox: true
    number-sections: true
    smooth-scroll: true
    anchor-sections: true
    fig-cap-location: margin
    tbl-cap-location: top
    bread-crumbs: false
    css:
    - styles.css
    - include/webex.css
    include-after-body: include/webex.js
search: true
execute:
  freeze: auto
