---
title: "Roma al Tempo di Benedetto"
description: "An analytical mapping method created by Giambattista Nolli"
categories: [Figure Ground Analysis, Public-Private Analysis]
tags: [analysis, map]
icon: "image/icon01.png"
date: 1748-01-01
---

# description and images

When most city maps were still birds's eye perspective views, Giambattista Nolli produced a map of 18th century Rome which greatly reduced and systematised the information contained in the map. Nolli limited himself to a 2d representation and only distinguished between public space (white) and private space (black). As a result, publicly accessible edge which otherwise remains hidden under the surface is instantly accessible. This is one of the basic goals of any analysis. Over the last decades, the Nolli map has mesmerised generations of urban designers, theorists and architects. Especially since the publication of "Learning from Las Vegas" (which also used the Nolli technique) dozens of "Nolli maps" have been produced.