---
title: "Urban Taxonomy"
author: "Martin Fleischmann and Krasen Samardzhiev"
description: "An analytical mapping method created by Giambattista Nolli"
categories: [Martin Fleischmann, urban taxonomy, Krasen Samardzhiev, morphometrics, quantitative analysis, data based, map based]
date-format: "YYYY"
date: "2025"
fig-cap-location: bottom
---

![Figure 1: Comparison of the urban fabric of Prague and Vienna. From The Hierarchical Morphotope Classification: A Theory-Driven Framework for Large-Scale Analysis of Built Form, by M. Fleischmann et al., 2025, (ArXiv:2509.10083). arXiv. https://doi.org/10.48550/arXiv.2509.10083. Licensed under CC BY 4.0.](../../images/urban_taxonomy.jpg){#fig-urban-taxonomy-1 fig-align="center"}

The Urban Taxonomy is an example of typology construction that uses hierarchical morphotope classification. It builds upon Conzen’s notion of a morphotope: the smallest unit of morphologically homogenous land and uses these to identify patterns and cluster morphologically similar areas together. This method works by ‘clustering’ similar points in a given dataset, thereby allowing you to identify different groups, or typologies. This approach allows you to process and analyse large datasets with many variables that would be impossible to do manually. In the Urban Taxonomy, patterns of urban form are classified into the following typologies of urban fabric: Coherent Interconnected Fabric, Coherent Dense Adjacent Fabric, Coherent Dense Disjoint Fabric, Incoherent Large-Scale Homogenous Fabric, Incoherent, Large-Scale Heterogenous Fabric, Incoherent Small-Scale Linear Fabric, Incoherent Small-Scale Sparse Fabric, and Incoherent Small-Scale Compact Fabric. As can be seen in Figure 1, the clear graphic style of an analysis like this allows you to easily compare between different cities at the same scale. 

## Links
[Urban Taxonomy](https://urbantaxonomy.org/)

## Methods
[Typology Construction (quantitative)](../../chapters/typology_construction_quantitative.qmd)

## Why use this method? 


## How does it work?


## You are ready to use this method if


## Questions you can answer 


## Steps


## Tools {#tools}


## Cases


## References


## Exercises


